name = "DipoleChain"
uuid = "a2a04298-baae-11e8-0c97-c92f7292435b"
authors = ["Dmitri Iouchtchenko <diouchtc@uwaterloo.ca>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
